id: a85299a147d446baadf6e1c62a70c22a
initial_creation_type: ocr
source_metadata:
  volumes:
    e8544c1d2c4e4def8140bdd5f0a08f6b:
      base_file: v081.txt
      image_group_id: I1PD95927
      title: ''
      total_pages: 1630
      volume_number: 82
